#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
pwd

# ESlint
ESLINT_STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$"))

echo "Checking ${#ESLINT_STAGED_FILES[@]} staged files for ESLint Errors..."

if [[ "$ESLINT_STAGED_FILES" != "" ]]; then
    
    # Check for eslint
    ESLINT="node_modules/.bin/eslint"
    if [[ ! -x "$ESLINT" ]]; then
        printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
        exit 1
    fi
    
    $ESLINT "${ESLINT_STAGED_FILES[@]}" --fix
    
    ESLINT_EXIT="$?"
    
    # Re-add files since they may have been fixed
    git add "${ESLINT_STAGED_FILES[@]}"
    
    if [[ "${ESLINT_EXIT}" == 0 ]]; then
        printf "\n\033[42mESlint checks passed\033[0m\n"
    else
        printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
        exit 1
    fi
fi

exit $?
