# See /aws/deploy.sh for steps executed after an ssh
name: AWS Staging Deployment

on:
  push:
    branches:
      # - main
      - aws-deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: Staging
      url: http://ec2-44-202-29-2.compute-1.amazonaws.com/

    steps:
      - name: Checkout client repo
        uses: actions/checkout@v3
        with:
          ref: aws-deploy

      - name: Print current working-directory
        run: |
          pwd
          ls -a

      - name: Execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ec2-44-202-29-2.compute-1.amazonaws.com
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: sh aws/deploy.sh
