# See /aws/deploy.sh for steps executed after an ssh
name: AWS Staging Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: Staging
      url: http://ec2-44-202-29-2.compute-1.amazonaws.com/

    steps:
      - name: Deploy to EC2 via ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ec2-44-202-29-2.compute-1.amazonaws.com
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd $HOME/LANE-client
            pwd
            git pull
            chmod u+x ./aws/deploy.sh
            sh ./aws/deploy.sh
