name: LANE_client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: # Note that env variables are only accessible from within a `steps` context
  NODE_VERSION: 16.15.0

jobs:
  eslint_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node dependencies
        run: npm ci

      - name: Eslint code check
        run: npm run lint:pr

  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node dependencies
        run: npm ci

      - name: Unit Tests
        run: npm run test

  client_builds_successfully:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout client repo
        uses: actions/checkout@v3
        with:
          path: client

      - name: Checkout server repo
        uses: actions/checkout@v3
        with:
          repository: dougUCN/LANE-server
          path: server
          submodules: recursive

      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node dependencies
        working-directory: client
        run: npm ci

      - name: Get schema from BE repo and generate Tsx file
        working-directory: client
        run: npm run generate:local

      - name: Build client
        working-directory: client
        run: npm run build
